language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: devcon5
    token: $SONAR_TOKEN

jdk:
  - openjdk11

jobs:
  include:
    - if: type != pull_request
      script: mvn clean package sonar:sonar
    - if: type = pull_request
      script: mvn clean package

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar/cache
