language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: devcon5
    token: $SONAR_TOKEN

jdk:
  - openjdk11

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report
  - if [ type != pull_request ]; then mvn sonar:sonar; fi

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar/cache
